---
apiVersion: v1
kind: Secret
metadata: 
  name: {{ template "fullname" . }}-auth
  labels:
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.version }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
stringData:
    userpass: "{{ .Values.security.username }}:{{ .Values.security.password }}"
