name: curator
version: 0.1.0
AppVersion: 0.1.0
description: Curator chart for managing elasticsearch indices
keywords:
- logging
- curator
- elasticsearch
- delete_indices
home: https://github.com/samsung-cnct/chart-curator
sources:
- https://github.com/samsung-cnct/chart-curator
maintainers:
- name: OSS Maintainers
  email: oss-maintainer@samsung-cnct.io
icon: https://github.com/samsung-cnct/solas/docs/images/samsung-logo.svg
engine: gotpl
