apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
data:
  action_file.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    actions:
      1:
        action: delete_indices
        description: >-
          Delete indices older than the specified period of time and prefixed
          with a pattern. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
{{ toYaml .Values.retention.options | indent 10 }}
        filters:
{{ toYaml .Values.filters | indent 10 }}

  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
{{ toYaml .Values.client | indent 6 }}
    logging:
{{ toYaml .Values.logging | indent 6 }}
